### ISSUE TITLE
built js not same as distributed js.

### ISSUE THREAD

**Issue by hezedu** [xtermjs/xterm.js#2090]
When I use built js. It's fine.

When I use distributed js directly. I will get an error:
Uncaught TypeError: term.onResize is not a function. 
[jsfiddle demo](https://jsfiddle.net/hezedu/ndv3f9gj/38/)

`demo/client.ts` caused it:
https://github.com/xtermjs/xterm.js/blob/610c4c9726402591fa783cdece0f1166fa3437a5/demo/client.ts#L96

Correct it:
`term.on('resize', (size) => {})` 
It work fine.

- Browser and browser version:  Chrome  74.0.3729.131
- OS version: win 10
- xterm.js version: 3.12.2

**Comment by hezedu** [comment]
```css
.xterm-dim {
    opacity: 0.5;
}

.xterm-underline {
    text-decoration: underline;
}

```
