### ISSUE TITLE
Textarea can shift the viewport's position when pressing space

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3058]
https://github.com/xtermjs/xterm.js/pull/2996 appears to have caused an issue where the textarea can mess with `.xterm-screen`'s position. A fix that works in VS Code is to add this:

```css
.xterm-helper-textarea {
	border: 0px;
}
```

Maybe this in combination with changing the textarea's font size to `Math.floor` instead of `Math.ceil` will be sufficient?
