### ISSUE TITLE
Can not input letter on Safari under specific input method

### ISSUE THREAD

**Issue by house-lee** [xtermjs/xterm.js#3396]
When using the Japanese input method (Romaji mode), I can not input any letter on Safari. But other browsers like Chrome & Firefox work fine.

## Details
- Browser and browser version:  Safari  [Version 14.1.1 (16611.2.7.1.4)]
- OS version: mcOS Big Sur 11.4
- xterm.js version: tried 4.7.0, also tried 4.13.0

### Steps to reproduce

1. on macOS, choose/activate "Japanese - Romaji" input method
2. under "Input Sources" tab of the setting panel, make sure "Romaji" mode is activated
3. go to https://xtermjs.org/ and scroll down to the demo section
4. switch the input method to Romaji, and then try type anything in the demo, nothing will show up
5. but ctrl+c/ctrl+v still works

**Comment by Tyriar** [comment]
Unconfirmed

**Comment by childrentime** [comment]
@Tyriar  It might be because of xterm's css style issue. 
```css
.xterm {
    position: relative;
    user-select: none;
    -ms-user-select: none;
    -webkit-user-select: none;
}
```
You can get reference from here. 
https://github.com/facebook/react/issues/16836
