### ISSUE TITLE
Can't input text in Safari 15 with InputMethodKit such as 搜狗拼音输入法

### ISSUE THREAD

**Issue by Innei** [xtermjs/xterm.js#3639]
Can't input text in Safari 15 with speical input source such as 搜狗拼音输入法 English mode.

## Details
- Browser and browser version: Safari 15.2
- OS version: macOS 12.2.1
- xterm.js version: 4.17.0

### Steps to reproduce

1. Go codesandbox https://codesandbox.io/s/intelligent-smoke-eovbu?file=/index.html
2. Open with Safari
3. Use [搜狗拼音输入法](https://pinyin.sogou.com/mac/)'s English mode to input text.

**It look like this issue: https://github.com/xtermjs/xterm.js/issues/3396**

**Comment by Innei** [comment]
https://user-images.githubusercontent.com/41265413/153812876-2065a3b2-1041-4bb9-9d3a-645fbd37c65d.mov

**Comment by Innei** [comment]
Chrome is work expected.

**Comment by childrentime** [comment]
@Innei  It might be because of xterm's css style issue. 
```css
.xterm {
    position: relative;
    user-select: none;
    -ms-user-select: none;
    -webkit-user-select: none;
}
```
You can get reference from here. 
https://github.com/facebook/react/issues/16836
