### ISSUE TITLE
Last char on the line not visible (wrapped) for some fonts

### ISSUE THREAD

**Issue by texcoffier** [xtermjs/xterm.js#4601]
## Details
- Browser and browser version: FireFox 115.0.1 (snap version)
- OS version: Ubuntu 22.04.2 LTS
- xterm.js version: 5.2.1

### Steps to reproduce
1. Display 80 characters on a line
2. Try some options.fontSize value until the last character disappear (wrapped).
    Size 21 or 24 in my case (may depends on installed fonts so difficult to reproduce).

If the cursor is moved on the hidden last char, it also disappear.

### Fix
The line element inline style is in my case:
```css
   {
     width: 812px;
     height: 21.3333px;
     line-height: 21.3333px;
     overflow: hidden;
   }
```
Two ways to fix:
1. Increase the width by 1 pixel (not very nice)
2. Add  `white-space: nowrap` (it is a more resilient fix)
