### ISSUE TITLE
Scrollbar is unclickable

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#512]
On latest chrome, if you cause xterm to generate a scrollbar, you are only able to scroll with the mousewheel. I can't click on the actual scrollbar on screen to drag it around.

I can sort of fix this by giving xterm-viewport absolute positioning and a z-index of 1 so it appears above xterm-rows.

**Comment by vincentwoo** [comment]
This doesn't seem to happen in Firefox.

Also, what do you think about changing [overflow-y on .terminal-viewport](https://github.com/sourcelair/xterm.js/blob/ca19da16e07930c1850104f1e1ce3245da1d2e3c/src/xterm.css#L148) to "auto" instead of "scroll". On Firefox and OSX Chrome (with an external mouse plugged in), xterm currently renders a scrollbar at all times, which might not be a great idea.

**Comment by Tyriar** [comment]
Does making the viewport higher with `z-index` mess with selection/focus on the terminal?

I haven't seen any of these issues on Electron, I do have it positioned using this though:

```
.xterm-viewport {
	/* Align the viewport to the bottom of the panel, just like the terminal */
	position: absolute;
	right: -20px;
	bottom: 0;
	left: 0;
}
```

**Comment by vincentwoo** [comment]
The z-index thing isn't great either because I get weird stuff like this: https://www.dropbox.com/s/ak4mbb5pn500k5k/Screenshot%202017-01-26%2016.31.49.png?raw=true (notice the scrollbar on the right clipping the text).

I'm actually not super sure what the correct solution should be, just wanted to bring this to your attention.

**Comment by JeromeVi** [comment]
For me in macOS Sierra with Chrome I don't have any scrollbar displayed despite when I inspect the source code there was `overflow-y:scroll;`  #563

**Comment by cheton** [comment]
This works for me. You can also detect whether the vertical scrollbar is visible, and set proper right position.

```css
.terminal .xterm-viewport {
    overflow-y: auto;
}
.terminal .xterm-rows {
    position: absolute;
    top: 0;
    left: 5px;
    right: 18px; /* Use "right: 0" if the vertical scrollbar it not visible */
    overflow: hidden;
}
```
