### ISSUE TITLE
Provide support for background image in terminal

### ISSUE THREAD

**Issue by zxdong262** [xtermjs/xterm.js#5235]
In previous versions when set css background image for .xterm-viewport use css
```css
#container .session-current .xterm-viewport {
    background-image: url("./images/electerm-watermark.png");
}
```

I can easily control terminal background, after uprade to latest release, .xterm-viewport is covering the terminal input, the background image would cover the user input layer

Can we get back the support for background image? Or there is another way to do it?

![Screen Shot 2024-12-06 at 18 08 49](https://github.com/user-attachments/assets/f20c2763-2637-4fe6-b8c7-1f32ff8990d6)
