### ISSUE TITLE
linear gradients for smooth color transitions between characters

### ISSUE THREAD

**Issue by 1Hyena** [xtermjs/xterm.js#5324]
With the `background-clip: text` CSS style property it is possible to have smooth color transitions between sequential letters in a text.

I propose making it an API option for xterm.js so that this behavior could be enabled by the application developer.

Here are some screenshots of a proof of concept terminal rendering of the requested feature:

![Image](https://github.com/user-attachments/assets/3a37be22-08ef-4421-8d11-cc1ac3914f6c)
(without color gradient)

![Image](https://github.com/user-attachments/assets/189aa423-838a-4633-88a3-9b8103361262)
(with color gradient)

![Image](https://github.com/user-attachments/assets/777c6c61-6034-43e7-b0d2-cbcde69acd14)
(gradient without the background-clip CSS property)

![Image](https://github.com/user-attachments/assets/f7cd820c-e448-42e6-9334-239e57c90b48)
(gradient with the background-clip CSS property, using 3 color points per gradient)

![Image](https://github.com/user-attachments/assets/687a1d0a-a5c2-459e-9cad-6856f1c3861d)
(gradient with the background-clip CSS property, using just 2 colors per gradient)

Below is a segment from the CSS that I used to let the browser render those images.

```CSS
td:is([data-x="63"][data-y="23"]) {
    /*color: lime;*/
    background-image: linear-gradient(to right, lime, #00c000);
    color: transparent;
    background-clip: text;
}

td:is([data-x="64"][data-y="23"]) {
    /*color: green;*/
    background-image: linear-gradient(to right, #00c000, green);
    color: transparent;
    background-clip: text;
}

td:is([data-x="65"][data-y="23"]) {
    /*color: green;*/
    background-image: linear-gradient(to right, green, #404000);
    color: transparent;
    background-clip: text;
}

td:is([data-x="66"][data-y="23"]) {
    /*color: maroon;*/
    background-image: linear-gradient(to right, #404000, maroon);
    color: transparent;
    background-clip: text;
}

td:is([data-x="67"][data-y="23"]) {
    /*color: maroon;*/
    background-image: linear-gradient(to right, maroon, #c00000);
    color: transparent;
    background-clip: text;
}

td:is([data-x="68"][data-y="23"]) {
    /*color: red;*/
    background-image: linear-gradient(to right, #c00000, red);
    color: transparent;
    background-clip: text;
}
```
